version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Match-app
    ports:
      - 8080:8080
    networks:
      match-networks:
    depends_on:
      - oracle-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Oracle=User Id=system;Password=oracle;Data Source=oracle-db:1521/XEPDB1
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
      

volumes:
  oracle-data:
networks:
  match-networks:
    driver: bridge